"""1

Revision ID: 8f71fa448701
Revises: 
Create Date: 2024-12-10 16:13:43.787131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f71fa448701'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jid', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('authenticated_use', sa.Integer(), server_default='100', nullable=False),
    sa.CheckConstraint('LENGTH(name) > 0', name='user_name_length_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jid', name='uq_user_jid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
