"""2

Revision ID: ae64d9e5eac6
Revises: 8f71fa448701
Create Date: 2025-01-21 09:36:27.653377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae64d9e5eac6'
down_revision: Union[str, None] = '8f71fa448701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product_line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['product_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'product_line_id')
    # ### end Alembic commands ###
